### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [MarkGodwin/tplink-omada-api#1]
It would be very helpful if you could tag releases as well. This would enable distributions who want to run your tests to fetch the package from GitHub instead of PyPI.

Thanks

**Comment by MarkGodwin** [comment]
Yeah, you're quite right. Turns out I actually forgot to push the v1.0.1 source code in the first place.
I've created a release tag for it now, and will accept your PR to add the upper version limit on `aiohttp`.
