### ISSUE TITLE
Ability to set client name

### ISSUE THREAD

**Issue by lyricnz** [MarkGodwin/tplink-omada-api#24]
It would be useful if there was a method to set the name/username for a device. Then we can use either a static list, or arp (!), to push human-readable names into the controller.

**Comment by lyricnz** [comment]
Looks like a PATCH to the client URL

```
{"name":"smartplug6","rateLimit":{"enable":false},"clientLockToApSetting":{"enable":false},"ipSetting":{"useFixedAddr":false}}
```

**Comment by lyricnz** [comment]
OK, found the API docs from https://community.tp-link.com/en/business/forum/topic/590430

And submitted the patch. Worked fine.

```python
                payload = {
                    "name": f'WAS {x.name}',
                    # "rateLimit": {
                    #     "enable": False
                    # },
                    "clientLockToApSetting": {
                        "enable": False,
                    },
                    "ipSetting": {
                        "useFixedAddr": False
                    }
                }
                result = await site_client._api.request(
                    "patch",
                    site_client._api.format_url(f"clients/{x.mac}", site_client._site_id),
                    payload=payload,
                )

```

**Comment by lyricnz** [comment]
FWIW the reason I ask is that the default "name" field appears to be mostly useless, and that's what's used on the map. I'd like to set each device to the name from the reverse-dns for the IP.  The controller already has most of the hostnames in a different column...

**Comment by MarkGodwin** [comment]
Yeah, I haven't added any parts of the clients api yet. When I do this, I will be sure to include this feature.
Or, if you want to submit a PR... :)

**Comment by D-J-See** [comment]
> Yeah, I haven't added any parts of the clients api yet. When I do this, I will be sure to include this feature. Or, if you want to submit a PR... :)

Hi @MarkGodwin Thanks for your work on this!
I am planning to add two new client functions - set-client-name and set-client-ip. Before I go too far, are they OK as new functions in omadasiteclient.py (set_client_name and set_client_ip), or you would you prefer other names or location?
