### ISSUE TITLE
Fails with self-signed certs - 

### ISSUE THREAD

**Issue by Coder84619** [MarkGodwin/tplink-omada-api#41]
I have a Omada controller install with self-signed certs. Connecting both via IP and FQDN fail. 

Cannot connect to host omada.xzy.com:8043 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')]

I'd like to see an override switch to not fail on self-signed cert.

**Comment by MarkGodwin** [comment]
Check out the help for the Omada target command. The option to disable ssl verify should be there.

**Comment by Coder84619** [comment]
Thank you.
