### ISSUE TITLE
Feature: Rename clients

### ISSUE THREAD

**Issue by Coder84619** [MarkGodwin/tplink-omada-api#43]
I'd love to see the wrapper to be able to rename (change the username) of a client device. Right now most of my client names are just MAC addresses which is not useful. Not sure the API supports a rename operation, but if it does, it would be super useful.

**Comment by MarkGodwin** [comment]
The omada cli already supports this with `omada set-client-name <mac> <name>`
Are you using the API directly or the command-line interface?

**Comment by MarkGodwin** [comment]
In Omada CLI 1.3.13 there is an alternative cli command with more features.
`omada client <mac or current name> --set-name "name"`
